version: "3.0"
services:
  samba-ad-docker:
    build: .
    image: $IMG_PREFIX/sambadocker
    # Add this hostname to /etc/hosts
    # and point it to 127.0.0.x
    hostname: $SMB_HOSTNAME
    container_name: sambad
    env_file: .env
    volumes:
       - samba_data:/var/lib/samba
    ports:
       # We only care about LDAP
       - "0.0.0.0:389:389"
       - "0.0.0.0:686:686"

volumes:
  samba_data:
