version: "3.0"
services:
  samba-ad-docker:
    build: .
    image: sad
    hostname: ldap.server.dev
    container_name: ldap
    cap_add:
      # Samba bruker extended attributes på filer
      - SYS_ADMIN
    environment:
      - SMB_ADMIN_PASSWORD=dette_ER_et%LANGTordSOMkanskjeERnok
    volumes:
      - /home/hildenae/src/sambadocker/../samba-data:/var/lib/samba
