version: "3.0"
services:
  samba-ad-docker:
    build: .
    image: sad
    hostname: ldap.server.dev
    container_name: ldap
    environment:
      - SMB_ADMIN_PASSWORD=dette_ER_et%LANGTordSOMkanskjeERnok
    volumes:
       - ./data:/var/lib/samba
    ports:
       - "127.0.0.2:1636:636"
